name: Generate SBOM using Custom Action

on:
  push:
    branches:
      - main

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 👇 Install cdxgen globally on the runner
      - name: Install cdxgen
        run: npm install -g @cyclonedx/cdxgen

      # 👇 Call your custom action
      - name: Run custom SBOM action
        uses: muskan-shah2025/NeoCustomWithDist@main
        id: generate_sbom

      - name: Show SBOM output
        run: |
          echo "SBOM:"
          echo "${{ steps.generate_sbom.outputs.sbom }}"
