name: Generate SBOM using Custom Action

on:
  push:
    branches:
      - main

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install cdxgen globally
      # - name: Install cdxgen
      #   run: npm install -g @cyclonedx/cdxgen

      # Run your custom action
      - name: Run custom SBOM action
        uses: muskan-shah2025/NeoCustomWithDist@main
        id: generate_sbom

      # Save SBOM output to a file
      # - name: Save SBOM to file
      #   run: echo "${{ steps.generate_sbom.outputs.sbom }}" > sbom.json

      # Upload SBOM file as an artifact
      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
