name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install cdxgen
        run: go install github.com/CycloneDX/cdxgen/cmd/cdxgen@latest

      - name: Add Go bin to PATH
        run: echo "${{ env.GOPATH }}/bin" >> $GITHUB_PATH

      - name: Install Node.js dependencies
        run: npm install

      - name: Run NeoCustom Action
        uses: muskan-shah2025/NeoCustomWithDist@v1.0.2
        id: neocustom
        with:
          who-to-greet: 'Muskan'

      - name: Show SBOM output
        run: |
          echo "SBOM: ${{ steps.neocustom.outputs.sbom }}"

